### ISSUE TITLE
Design new place for Key Personnel in the expanded APD structure

### ISSUE THREAD

**Issue by beparticular** [Enterprise-CMCS/eAPD#2518]
Key Personnel currently are entered at the beginning of an APD. They are calculated as part of the budget for Activity 1 for HITECH APDs. 
KP doesn't have to be part of this Activity and is confusing to users so we can explore a new way to handle KP in the expanded structure. 

Assumptions: KP would be better entered within the Activities section, since they cover all/each Activities. The budget should be shown separately since KP isn't calculated as part of an Activity. 

If we move the KP out of the state staff table, we'll need to determine what calculations will change. 

In addition - the HIT and HIE required fields need to be removed from the KSP section. Does that mean we need to move the costs forward? Let's proceed with costs in Activities, and have the removal from the current KSP be holistic and clear. See next paragraph. 

**Key State Personnel**
The KSP should only be the primary point of contact for this APD. 
- Total cost from Key Personnel ("Does this person have costs directly attributable to this program? and following questions.")
- "Add Key Personnel" button (why would this be removed? - JD)

### This task is done when...
 - [x] Determine where KP should live (within Activities section, outside Activities section?) 
 - [x] Determine where the KP Budget summary should live (top of Budget Summary page?) 
 - [ ] Determine what calculations will change as a result of this move
 - [x] Designs are created (don't forget to change label on add button and styling to match Activity List)
 - [x] Designs are approved by product
 - [ ] Additional design/dev tickets are created as needed

**Comment by aricka-lewis** [comment]
No need to identify costs -- remove these for Key Personnel. 
In respective activities, list relevant personnel

**Comment by akuas** [comment]
One suggestion presented about Key State Personnel is " just listing them and having the State decide where they want to list any costs associated wit them."

**Comment by akuas** [comment]
@SGilliamA1M @jeromeleecms Here is my work in progress for the key state personnel. 
[Key State Personnel with updated help text and FFP](https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=1865%3A14195)
[Proposed Budget with KP Totals](https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=1610%3A14175)

**Comment by jeromeleecms** [comment]
That sounds interesting. Since there is no place that shows an itemized view for each of the Key Personnel, it seems like this section would be the only place to put it before a user completes the review. @thetif How much of a lift would this be? Or had you planned for only showing the summary cost for Key Personnel in this section?

For the second question, for now we are assuming that MMIS will be the only funding source. My understanding is that we were removing the funding source option at the activities. There may be situations where a project may cross funding sources, but we may have to consider this later and have to add E&E in. Maybe a @thetif as well - did you model the math updates to assume each APD was based on a single funding source or is it like the activities where you could add a funding source and the math calculates differently?

**Comment by akuas** [comment]
Notes from parking lot: Nov 7th 2022
1. **The Plan**: Add the key state line item to summary budget, add itemized key state personnel to somewhere in the proposed budget (most likely the activity breakdown), and add FFP to the key state personnel subform below the total
2. Key Personnel is an individual who may or may not be dedicated the entire time to project. 
3. Cost with benefits refers to their salary over the ffy including all the different projects they are doing. Most of the time how much they are paid is consistent along their projects.
4. If their cost with benefits is $100,000 and they spend 0.25 of their time on one project, then their total is $25,000
5. Their FFP is then applied to the $25,000 total not the larger cost with benefits
6. Possibly out of the scope of this ticket we have to think about whether folks should put in the same key personnel twice if they have different ffp

**Comment by thetif** [comment]
I modeled the budget off of what we have for HITECH, but removed everything except for MMIS. It will be easier to make shared frontends of the structure is pretty similar.

**Comment by akuas** [comment]
@thetif Thats good to know.

**Comment by akuas** [comment]
@jeromeleecms Can you please review this ticket? The designs are linked below. Again no rush on this. 
[Key State Person Design](https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=1901%3A15176)
[Proposed Budget Design](https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=1992%3A16701)

**Comment by akuas** [comment]
### Closing Notes
## Key State Personnel
1. The 3rd line in the Key Personnel and Program Management needs to be revised to say "Key personnel costs entered here are represented in the Proposed Budget, at the FFP specified below."
2. The example box copy has changed,
3. The hint text for total  has been added to explain the rationale behind the math. "Cost with benefits x FTE = Total"
4. An abridged Federal State Split is added to the subform that will appear if they select yes. There are only 2 options because Key State Personnel would likely only select funding at these match rates.

Proposed Budget
1. Summary Budget Table

**Comment by akuas** [comment]
@mirano-darren Can you please review this and let me know if you have any questions?

**Comment by akuas** [comment]
@stephanieboydcms For awareness, this a ticket I was recently working on. Feel free to reach out if you want additional context behind this work

**Comment by akuas** [comment]
@thetif Can you please review this ticket? I will be demoing it in the next couple of days, but feel free to let me know if there is anything unclear about how it works in the meantime.

**Comment by mirano-darren** [comment]
These changes are looking good! Very clear and concise to me. One question:
- Is a Primary APD Point of Contact required? Would admin check catch this as an error?

**Comment by akuas** [comment]
@mirano-darren The first key personnel entered is always the Primary APD Point of Contact. So, if there isn't one, then the page would like how it looks when no key personnel is added.

**Comment by akuas** [comment]
@SGilliamA1M Can you review this ticket?

**Comment by SGilliamA1M** [comment]
@akuas changes look good. Please see comments regarding adding the correct navigation bar to the designs and providing annotations for required fields. Thanks

**Comment by akuas** [comment]
@SGilliamA1M Thanks, I made the changes

**Comment by akuas** [comment]
@thetif This ticket is ready for dev! :)

**Comment by thetif** [comment]
created dev tickets #4413 and #4416
