### ISSUE TITLE
[Design issue] Update export view to reflect MMIS expansion

### ISSUE THREAD

**Issue by aricka-lewis** [Enterprise-CMCS/eAPD#3693]
We may have done this on this page in Figma: 
https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2022?node-id=0%3A16744

### This task is done when...

- [x]  Design APD Overview
- [x] Design Key State Personnel
- [x] Design State Scope and Priorities 
- [x] Design Results of Previous Activities 
- [x] Design Activities Dashboard
- [x] Design Activity Overview
- [x] Design Analysis of Alt and Risks
- [x] Design Activity Schedule and Milestones 
- [x] Design Conditions for Enhanced Funding
- [x] Design State Staff and Expenses
- [x] Design Cost Allocation and Other Funding
- [x] Design Budget and FFP
- [x] Design Activity Schedule and Summary
- [x] Design Security Planning
- [x] Design Assurances and Compliance
- [x] Update the MMIS Changes file when done
- [x] 508 considerations and/or recommendations are reviewed
- [x] designs are shared
- [ ] designs are approved by product
- [x] if there is a long discussion, a summary of changes for dev will be added to the last comment before transfer
- [x] a list of changes to be made if this is improving an existing feature
---

**Comment by aricka-lewis** [comment]
- change MMIS submission email address

**Comment by akuas** [comment]
Closing Notes (in progress)
1. [Key State Personnel](https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=3548%3A20974&t=UFSiP35PqUiJ6KiC-1): 
>  - Updated section to reflect total field addition. 
> - Key State Personnel empty subform message : No Medicaid director and corresponding Medicaid office address was provided.
> - Key State Personnel and Program Management empty subform message: No key state personnel was added.

2. [State Scope and Priorities](https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=3548%3A21085&t=UFSiP35PqUiJ6KiC-1)

3.

**Comment by akuas** [comment]
@jeromeleecms and @stephanieboydcms can you please review this ticket.I will update the closing notes once the issue with zenhub comments is resolved. But below is the export in its entirety, showing the export filled out and in an empty state. 
[Export View Filled In](https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=3674%3A23279&t=A0P4M0BoZQUOmpIo-1)
[Export View Empty State](https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=3725%3A25149&t=A0P4M0BoZQUOmpIo-1)
Disclaimer
1. The math will not add up. The export design is not meant to be looked at as a cohesive APD, just a demonstration of the design. In the same vein there might be situations, where I list 1 ffy and some that I list 2 ffy.
2. I just focused on the pages above because those were the ones that Tif pointed out was needed. If it is not listed above, the design did not change.

**Comment by stephanieboydcms** [comment]
Thank you for a chance to review @akuas .  I left minor alignment and such comments in Figma.  Great job!

**Comment by akuas** [comment]
## Closing Notes
[Full Export View: Filled Out](https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=3674%3A23279&t=gR0ruQfnY9X5gA8C-1)
[Full Export View: Empty/Unanswered Fields](https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=3725%3A25149&t=gR0ruQfnY9X5gA8C-1)
1. Executive Summary
> - The Executive Summary Section is unchanged.
> - The Program Budget Tables changed to reflect table redesign.
> - MMIS M&O not shown if there are no M&O activities

**Comment by akuas** [comment]
@jeromeleecms I made the changes that you and Stephanie proposed, so if there is nothing else, I think this design is ready for dev.

**Comment by stephanieboydcms** [comment]
@akuas I had one minor alignment comment I left in Figma.  Once that is fixed I am good for my review, pending @jeromeleecms , I am good to push.  Great work Akua!

**Comment by akuas** [comment]
@stephanieboydcms Thanks for the review!
Ditto of Stephanie's comment, I have made the changes that you both proposed, and I think this is ready for dev.

**Comment by jeromeleecms** [comment]
@akuas Just a couple final comments. Noted in the Figma, but:

1) The addition of the FFP match at the beginning of the activity description is fine, but it should show the FFYs since the FFP for each year is managed independently.
2) The Key Personnel in the Filled Out version of the design still shows that it's in Activity 1. It's correct in the closing notes and the empty state, but the filled out version should show KP in the separate table.

Everything else looks good. Can you also spin up a design ticket to capture the idea of converting the milestones into a table in the export/read only view?

**Comment by akuas** [comment]
@jeromeleecms For the 2nd point, I removed key state personnel from the activity 1. I think you are suggesting have a separate kp table there. We don't currently do that the for the budget and ffp and I don't think it is needed because the budget and ffp is at the activity level not apd level. So, if we add the kp table it would be shown by ffy not by activity. It makes sense to have the kp table in the proposed budget, but not here, in my opinion. What do you think?

**Comment by jeromeleecms** [comment]
@akuas You are correct, activity 1 shouldn't have any KP data in it all all. In the filled out version of the Figma, I'm still seeing them.

![image](https://user-images.githubusercontent.com/34279968/217300619-0aa689cf-a154-45d1-8e0d-da971ce94acd.png)

But yes, KP by FFY in the proposed budget is perfect.

**Comment by akuas** [comment]
@jeromeleecms I missed that one, but made the change. Now, I think it is ready for dev.

**Comment by jeromeleecms** [comment]
Thanks @akuas. @thetif This is ready for dev. This also includes the updated language that you made for "Medicaid Total Computable by FFY" in your other ticket.

**Comment by thetif** [comment]
created dev tickets
* #4553
* #4554
* #4555
* #4556
* #4557
* #4558
* #4559
* #4560
* #4561

**Comment by jeromeleecms** [comment]
@SGilliamA1M This overlaps with #4488 and some of them are already being worked on. If this is good to close, we can close this design ticket.

**Comment by jeromeleecms** [comment]
Good to close.
