### ISSUE TITLE
[Dev] Implement MMIS APD Overview

### ISSUE THREAD

**Issue by mirano-darren** [Enterprise-CMCS/eAPD#4211]
### Description and related issues
The MMIS APD Overview page will be different from the current APD Overview page.  The fields from the Create new APD page will live in this page. **APD Type cannot be changed**

**Update the component to have the following shared fields:**
* APD Name
* What type of APD are you creating (read-only, disabled)
* FFY 
* Is an APD Update?

**for HITECH the fields will stay the same:**
* Introduction
* HIT Overview
* HIE Overview
* MMIS Overview

**for MMIS the fields will be:**
* Medicaid Business Area

### Behind the scene changes:
* adding new set methods in actions/editApd/overview.js to handle saving the new fields

Schema for updated HIT:
```json
...
apdOverview: {
  updateStatus: {
    isUpdateAPD: Boolean,
    annualUpdate: Boolean,
    asNeededUpdate: Boolean
  },
  programOverview: String,
  narrativeHIT: String,
  narrativeHIE: String,
  narrativeMMIS: String
},
...
```

Schema for update MMIS:
```json
...
apdOverview: {
  updateStatus: {
     isUpdateAPD: Boolean,
     annualUpdate: Boolean,
     asNeededUpdate: Boolean
   },
   medicaidBusinessAreas: {
     waiverSupportSystems: Boolean,
     assetVerificationSystem: Boolean,
     claimsProcessing: Boolean,
     decisionSupportSystemDW: Boolean,
     electronicVisitVerification: Boolean,
     encounterProcessingSystemMCS: Boolean,
     financialManagement: Boolean,
     healthInformationExchange: Boolean,
     longTermServicesSupports: Boolean,
     memberManagement: Boolean,
     pharmacyBenefitManagementPOS: Boolean,
     programIntegrity: Boolean,
     providerManagement: Boolean,
     thirdPartyLiability: Boolean,
     other: Boolean,
     otherMedicaidBusinessAreas: String
   }
},
...
```

**Update the error message for APD Name**
The current behavior of the APD name field does not allow the user to enter a blank name. On blur, if the field is blank, the name will default to "Untitled IAPD". So for validation on this field, check if the name matches this default name.

Validation error message language: "Provide your own APD Name"

Design ticket: #4179
Figma link:  https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=414%3A10804

Test Cases:
| Given  | When | Then | 
| ------------- | ------------- | ------------- |
| APD Type Field | On the APD Overview page | This field cannot be changed and should be grayed out |
| An invalid APD Name | blurring out of the field | the error message will appear whether adminCheck is on or off |
| APD Overview Page | Admin check is on | If field is blank, inline validation should appear. Refer to this dev ticket for error language: #4209
| APD Overview Page | Right after creating a new APD | Green header should appear on the page informing the user they successfully created an APD. Header should **only** appear after first creating an APD.| 
| APD Overview Page | Right after creating a new APD | Selections should be the same from the Create new APD page | 
| APD Overview Page | Clicking the Continue button | Should redirect you to the state scope and priorities page (out of scope of this ticket) | 

### This task is done when...

- [ ] APD Overview for MMIS has been updated to match the designs
- [ ] APD Overview for HITECH still works and looks like previously did, but with the new shared field
- [ ] validation is working for APD Name on blur
- [ ] validation is working for the rest of the form when admin check is on
- [ ]  admin check catches when an APD has the name "Untitled"
- [ ] APD name field in create new APD page has inline validation on blur when name defaults to "Untitled"

**Comment by akuas** [comment]
Updated Closing Notes as of September 20, 2022 [Final Designs](https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=414%3A10804)

1. The page is called “Create a New Advanced Planning Document (APD)” when you are creating the APD. The page is called “APD Overview,” once an APD is created and when you return to the page. It appears on top of the side nav and will be the first page folks see after creating an APD.
2. Validation in Create a New Advanced Planning Document required all fields to be complete before continuing like a subform. Validation in APD Overview behaves like other pages in the builder and will be triggered by the admin check.
3. State Priorities and Scope is the old MMIS APD Overview without FFY.
4. The page starts off with a progressive disclosure, meaning we will only show the “What type of APD are you creating?” field and branch following fields, according to their selection
5. What type of APD are you creating?
    1. Alert disappears once they have created the APD
    2. If users want to change their selection after creating an APD, they would have to start a new APD.
    3. Changing from the HITECH IAPD to MMIS IAPD field selection would change your view (available fields).
    4. Both options come with a tooltip. When you hover over the tooltip it will define HITECH IAPD and MMIS IAPD acroymn.
    5. This field is in its intermediate state. When MMIS PAPD, OAPD and E&E are available, we will break up the field by funding source (HITECH, MMIS & E&E) and APD type (planning, implementation, and operations).
    6. Selecting HITECH IAPD opens up the APD name, FFY, and Update Type fields.
    7. Selecting MMIS IAPD makes APD name, FFY, Is this APD an update (Update Type if you select yes) and Medicaid Business Areas available.
6. APD Name: Puts name on header like before when you create an APD and can be revised from the header or on this page  after creating an APD
7. FFY: Moved from old APD Overview
    1. Validation is the same with the page level validation. 
    2. Two FFY selected as a default. Typically, we don’t pre-select options but the APD  and export breaks if you dont have FFY, so it’s important to keep a selection.
8. Is this an update: Available for MMIS only.
    1. Will be used to gather data on what types of APD folks are creating. ‘Yes’ option expands to provide ‘Update Type,’ which is required if you select yes for ‘Is this an update.’
9. Medicaid Business Area: The Medicaid MES Certification Repository will direct you to the CMS Certification GitHub: [https://cmsgov.github.io/CMCS-DSG-DSS-Certification/](https://cmsgov.github.io/CMCS-DSG-DSS-Certification/) . This list is subject to change so we will need a way to keep it updated. Eligibility and Enrollment is removed from the list. We may bring it back when E&E is available. MES Business areas are like meta tags like APD updates, at the moment. For MVP, it will not trigger a change in help text and fields in the same way the Funding Source/APD type field will be. So, the business areas can be changed after creating a new APD. Also we don't need to add mes business areas for HITECH because it is automatically HIT.
10. Cancel will direct you back to the dashboard and delete progress of this form. (this is the same as the subforms). The ‘cancel’ button disappears in APD Overview (once you have created an APD and are returning to the page)
11. The Create an APD button is disabled until you complete the form. It will have a tooltip indicating that all fields are required to create an apd when hovered over in its disabled state.

**Comment by akuas** [comment]
@mirano-darren Here are the closing notes. I will also copy it into Dev: Create front end for Create new APD.

**Comment by akuas** [comment]
@SGilliamA1M For awareness, this ticket represents the 2nd part of the create new apd/apd overview flow

**Comment by jeromeleecms** [comment]
Could we review this in parking lot @mirano-darren? I don't think the test cases line up with what this "APD Overview Page" - this seems to line up more closely with the create new APD flow from #4209.

**Comment by stephanieboydcms** [comment]
I have reviewed and this is good to move forward.  Thanks @amyd11 !
