### ISSUE TITLE
[Testing] Explore changing the cypress fixtures to match the APD format

### ISSUE THREAD

**Issue by thetif** [Enterprise-CMCS/eAPD#4447]
### Description and related issues
We need to investigate how difficult it would be to change the format of the APD fixtures in cypress. If they matched the ADP format then it would be easier to create them and to get the budget values for them.

### This task is done when…

- [x] determine the level of effort needed to change the Cypress fixtures
- [ ] determine the level of effort of maintaining the current format
- [ ] if applicable, create a ticket to change the format

**Comment by mirano-darren** [comment]
Initial thoughts:

- This should be done only for MMIS Cypress tests, It would a huge lift to refactor the HITECH fixtures to work with this new format, especially since HITECH work is going away soon.
- Does one fixture file = one APD seed? If so what types of APD are we going to need?
  - A functionally complete APD
  - An APD with purposely uncompleted fields 
  - Anything else?
- In general, it will be hard to match the format exactly. Some of the values in the format we have now are hardcoded in (specifically the years). To make the fixtures match this format we will also have to hardcode in these values (which we tried to avoid previously to make them reusable)
- We will also have to add in tables that are not inputs. These are not included in the seed format

**Comment by mirano-darren** [comment]
Note on future MMIS Cypress tests:

- My idea of what test suites we can have:
  - MMIS Basics: Tests out the functionality of new MMIS pages individually
  - MMIS Complete: Test creating a new MMIS APD from start to finish
  - Others?

**Comment by mirano-darren** [comment]
created #4469 for future work on this
