### ISSUE TITLE
[Bug] Key State Personnel being added to Executive Summary - Activities Totals

### ISSUE THREAD

**Issue by tbolt** [Enterprise-CMCS/eAPD#4672]
### Description
As noted in [this comment on the 4474 PR](https://github.com/Enterprise-CMCS/eAPD/pull/4636#issuecomment-1507211375) the key state personnel totals are being added to the activities section in executive summary for MMIS APDs. Key State Personnel in MMIS are not supposed to be a part of the activities totals.

### Steps to reproduce
1. Create new MMIS APD
2. Add a key state personnel
3. View Executive Summary and note that the budget is adding the key state personnel to activities section (see screenshot below)

**Expected results-**
In MMIS APDs Key State Personnel are _not_ added to the activities totals

**Actual results-**

### Role Affected

- [ ] All
- [ ] Federal Admin
- [x] State Admin
- [x] State Staff
- [x] State Contractor
- [ ] System Admin

### Environment

- [x] All
- [ ] PR #\_\_\_\_
- [ ] Staging
- [ ] Production

### Browser

- [ ] All
- [ ] Firefox
- [ ] Chrome
- [ ] IE

**Logs or error output/Screenshot/Video-** (at least 1 of these)
![Screenshot 2023-04-13 at 1.48.30 PM.png](https://images.zenhubusercontent.com/5f43eb2204d6d70d8324232c/8b6e2119-f956-42e8-937f-9ae12e7fd459)

**Comment by amyd11** [comment]
The changes to resolve this bug involve some UI tweaking such as modifying the section titles. This makes it clearer that these totals are not just the totals of the activities, but the overall total cost. The total cost should include both activities and key state personnel.

If we want to include the total cost of activities without key state personnel as part of the Executive Summary then it’s recommended to do that in another ticket since we want these values to be part of the budget data. The ticket should include updates to the budget model to add the necessary fields for these calculated values and updates to the calculateBudget function for the computations of those values.
